### ISSUE TITLE
v0.1  Release Website Tracker

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/multinet-website#1]
Overview: We need to create a release website to accompany ManifoldRG/MultiNet#196. The Website for Multinet might need to have several pages our outlinks to cover relevant artifacts. Scope of the Website for v0.1 is as follows:

* MultiNet Home Page w/ vision, etc
  * Link to dataset spec paper
  * links or subpages for releases
  * link to changelog/updates
  * Video Overview of MultiNet

* v0.1 OpenX Results Page (w/ name for OpenVLA release)
  * Link to OpenX Results Paper
  * Figures/Overview of Process
  * Video Overview of the Results

**Comment by harshsikka** [comment]
Website deployed and working here. will work w/ the team to fill out the content in the coming days.

**Comment by harshsikka** [comment]
For V0.1 Page
- [ ] Overhaul Content (notes in chat)

**Comment by pranavguru** [comment]
v0.1 website - https://multinet.ai/static/pages/Multinetv01.html
